---
pagetitle: CV
title: <center>Liza Wood</center>
subtitle: <center>Center for Environmental Policy & Behavior <br> University of California, Davis </center>
---
<center> <i class="fa fa-envelope-square" aria-hidden="true"></i> belwood@ucdavis.edu | [<i class="fa fa-globe" aria-hidden="true"></i> website](https://lizawood5.github.io/)</center>

***

#### EDUCATION

Ph.D. Student, Ecology | Designated Emphasis: Computational Social Science <span style="float:right;">2018 – present</span>  
University of California Davis, Davis, CA  
M.Sc., Organic Farming and Food Production Systems                        <span style="float:right;">2015</span>  
Newcastle University, Newcastle upon Tyne, United Kingdom  
M.Sc., Sustainability Science and Policy		            	               <span style="float:right;">2014</span>  
Maastricht University, Maastricht, Netherlands  
B.A., Political Science | B.A., Biology 		             	   	           <span style="float:right;">2013</span>  
Honors College at the College of Charleston, Charleston, SC  

***

<h4>SELECTED FELLOWSHIPS & AWARDS</h4>

Western Sustainable Agriculture Research & Education Graduate Student Grant | Davis, CA  <span style="float:right;">2020 – 2022</span>  
Ford Foundation Fellowship Program, Honorable Mention <span style="float:right;">2020</span>  
UC Davis Muir Institute Graduate Fellowship | Davis, CA<span style="float:right;">2019 – 2020</span>  
UC Davis Henry A. Jastro Student Research Fellowship | Davis, CA<span style="float:right;">2019 – 2020</span>    
UC Davis Graduate Group in Ecology Fellowship | Davis, CA<span style="float:right;">2018 – 2020</span>    
Rotary Foundation Global Grant Scholarship | Newcastle, United Kingdom<span style="float:right;">2014 – 2015</span>    
Fulbright Full Grant | Maastricht, Netherlands<span style="float:right;">2013 – 2014</span>   
ASIANetwork/Freeman-Asia Foundation Student-Faculty Fellowship | Isaan, Thailand<span style="float:right;">       2012</span>   
College of Charleston Summer Undergraduate Research with Faculty Grant | Charleston, SC<span style="float:right;"> 2011</span>  

***

<h4>PEER-REVIEWED PUBLICATIONS</h4>   

Rudnick, J., Lubell, M., Khalsa, S.D.S., Tatge, S., **Wood, L.**, Sears, M., Brown, P. (2021). A Farm Systems Approach to the Adoption of Sustainable Nitrogen Management Practices in California. *Agriculture and Human Values.* https://doi.org/10.1007/s10460-021-10190-5.  
Wang, J., Hasanalieva, G., **Wood, L.**, et al. (2020). Effect of wheat species (Triticum aestivum vs T. spelta), farming system (organic vs conventional) and flour type (wholegrain vs white) on composition of wheat flour – Results of a retail survey in the UK and Germany – 3. Pesticide residue content. *Food Chemistry: X 7*, 100089. https://doi.org/10.1016/j.fochx.2020.100089.  
Wang, J., Chatzidimitriou, E., **Wood, L.**, et al. (2020). Effect of wheat species (*Triticum aestivum* vs *T. spelta*), farming system (organic vs conventional) and flour type (wholegrain vs white) on composition of wheat flour; results of a retail survey in the UK and Germany – 2. Antioxidant activity, and phenolic and mineral content. *Food Chemistry: X 6*, 100091. https://doi.org/10.1016/j.fochx.2020.100091.  
Wang, J., Hasanalieva, G., **Wood, L.**, et al. (2020). Effect of wheat species (*Triticum aestivum* vs *T. spelta*), farming system (organic vs conventional) and flour type (wholegrain vs white) on composition of wheat flour; results of a retail survey in the UK and Germany – 1. Mycotoxin content. *Food Chemistry 327*, 127011. https://doi.org/10.1016/j.foodchem.2020.127011.  
**Wood, L**. & Welch, A. (2015). Assessment of interactive effects of elevated salinity and three pesticides on life history and behavior of southern toad (*Anaxyrus terrestris*) tadpoles. *Environmental Toxicology & Chemistry* 34(3), 667-676. https://doi.org/10.1002/etc.2861.

***

<h4>OTHER PUBLICATIONS</h4>  

Chaffin, L., Korey, C., Warnick, D., & **Wood, L**. (2019). Life So Far: A Grounded Theory Analysis of College Student Transitions Through the Sophomore Year. [Journal of The First Year Experience & Students in Transition](https://www.ingentaconnect.com/contentone/fyesit/fyesit/2019/00000031/00000002/art00005;jsessionid=21loj16kr9mnp.x-ic-live-01) 31(2), 79-93.  
**Wood, L**. (2014). Mo’ meat, mo’ problems: An assessment of lab cultured meat and food system transitions. [Maastricht University Journal of Sustainability Studies](https://openjournals.maastrichtuniversity.nl/SustainabilityStudies/issue/view/6) 2, 41-46.   
**Wood, L**. (2013). “Sowing sustainability: Rice commodity pathways, NGOs, and farmers’ engagement with alternative agriculture in northeastern Thailand.” [Growing Sustainable Communities: A Development Guide for Southeast Asia.](https://books.google.com/books/about/Growing_Sustainable_Communities.html?id=sTtZAQAACAAJ&source=kp_book_description) (pp. 111-151). Ed. Brennan, L., Fien, J., Parker, L., Duong, H., Anh Doan, M., & Watne. T. Australia: Tilde University Press.  
**Wood, L.** (2013). Balancing commodities and culture: Alternative agriculture and the viable indigenous model. [Chrestomathy, College of Charleston](https://chrestomathy.cofc.edu/documents/vol12/wood.pdf), 12, 1-31.

***

<h4>SELECTED PRESENTATIONS</h4>  

**Wood, L**. & Rudnick, J. (2020, April). “The effect of information-based policy tools on farmers’ nitrogen management.” American Association of Geographers Annual Meeting (remote).    
**Wood, L**. (2019, July). “Assessing Seed System Resilience: A Case Study from Northeastern Thailand.” International Association for the Study of the Commons, Lima, Peru.  
Korey, C., **Wood, L**. & Warnick, C. (2017, October). “FYEvolution: Multiple Transitions Revealed Through Student Voice Assessment.” Students in Transition, Costa Mesa, CA.  
Korey, C. & **Wood, L**. (2017, February). “Life So Far – Student Voice as an Assessment Tool.” First-Year Experience Conference, Atlanta, GA.  
**Wood, L**. (2015, February). “Mo’ meat, mo’ problems: An assessment of cultured meat and food system transitions.” Maastricht University Sustainability Journal Symposium, remote presentation.  
**Wood, L**. & Delfeld, H. (2012, September). “Non-governmental agricultural movements and rice commodity systems.” 2nd Workshop on Anticommodities: Local Forms Of Production As Resistance Against Market Domination. Wageningen, Netherlands.  
**Wood, L**. & Welch, A. (2012, January). “Tadpole responses to environmental stressors – pesticides and salinity.” Society for Integrative and Comparative Biology, Charleston, SC.   

***

<h4>RESEARCH EXPERIENCE</h4> 

**3 Revolutions for Future Mobility Program**<span style="float:right;">2020 – present</span>  
  University of California, Davis | PI: Dr. Tyler Scott   
  Employing computational methods to understand knowledge transfer in transportation policy, and the role of science and technology resources used in transportation governance   
**CDFA Fertilizer Research and Education Program**<span style="float:right;">2019 – 2020</span>  
  University of California, Davis | PI: Dr. Mark Lubell   
  Researching how information-based policy tools affect farmer conservation behavior related to soil nitrogen management in the Central Valley  
**Horticulture Innovation Lab & USAID**<span style="float:right;">2019</span>	 
  University of California, Davis | PI: Dr. Elizabeth Mitcham   
  Reviewed the lab’s projects in the context of innovation diffusion theories to glean generalizable findings regarding technology adoption for sustainable international development   
**European Union Healthy Minor Cereals Project**<span style="float:right;">2014 – 2015</span>   
  Newcastle University | PI: Dr. Carlo Leifert   
  Evaluated crop quality of spelt grown under organic intensification strategies in Greece and compared nutritional value of organic and conventional spelt and wheat flour in laboratory assays  
**Centre for Integrated assessment & Sustainable Development**<span style="float:right;">2013 – 2014</span>  
  Maastricht University | PI: Dr. Pieter Glasbergen   
  Developed sustainability criteria for climate change adaptation strategies to evaluate four major certification standards and conducted action research with Dutch-based NGO, Solidaridad  
**ASIANetwork & Freeman Asia Foundation**<span style="float:right;">2012 – 2013</span>    
  College of Charleston | PI: Dr. Helen Delfeld  				          		 
  Conducted survey research to understand cultural narratives related to rice varieties in NE Thailand and the role of alternative markets in the rice commodity supply chain  
**Welch Herpetology Lab**<span style="float:right;">2011 – 2013</span>  
  College of Charleston | PI: Dr. Allison Welch			      
  Evaluated the impacts of anthropogenic environmental stressors (sublethal levels of salinity and     pesticides) on the activity, growth, and survival of tadpoles in laboratory assays  

***

<h4>TEACHING EXPERIENCE</h4>  

**Instructor** | Ecology Graduate Group, UC Davis  
  ECL 298: R Data Analysis for Visualization in Science<span style="float:right;">Fall 2020</span>  
**Teaching Assistant** | Plant Sciences; Environmental Science & Policy; America Studies, UC Davis</span>   
  PLS 49: Organic Crop Production Practicum<span style="float:right;">Fall 2019, Spring 2020</span>   
  ESP 10: Current Issues in the Environment<span style="float:right;">Winter 2019</span>    
  AMS 10: Introduction to American Studies<span style="float:right;">Fall 2018</span>    
**Instructor** | Environmental Studies, College of Charleston  
  FYET 177: Sustainable Food in the Foothills of the Andes<span style="float:right;">Spring 2017 – 2019</span>     
  FYSE 142: Farm to Fork: The Sustainable Food Movement in Charleston<span style="float:right;">Spring 2018</span>    

***

<h4>PROFESSIONAL EXPERIENCE</h4>  

Consulting Researcher | Environmental Social Research Analysis LLC <span style="float:right;">2020 – 2021</span>   
First Year Experience Assistant Director | College of Charleston <span style="float:right;">2016 – 2018</span>   
Environmental Studies Adjunct Instructor | College of Charleston <span style="float:right;">2017 – 2019</span>   
Climate Change & Agricultural Adaptation Intern | Solidaridad Network <span style="float:right;">2013 – 2014</span>  
Climate & Fisheries Extension Researcher | SC Sea Grant Consortium <span style="float:right;">2012 – 2013</span>  

***

<h4>SERVICE</h4>

Data Carpentries Instructor | The Carpentries <span style="float:right;">2021 – present</span>   
R-Ladies Member & Facilitator| R-Ladies UC Davis <span style="float:right;">2019 – present</span>   
Sustainability Literacy Implementation Committee Member | College of Charleston <span style="float:right;">2017 – 2018</span>   
Faculty for Sustainable Living Workshop Coordinator | College of Charleston <span style="float:right;">2016 – 2018</span>   
Sociology of Food Service-Learning Liaison | College of Charleston <span style="float:right;">2016 – 2017</span>   
Student Union Council Representative & Secretary | Newcastle University <span style="float:right;">2014 – 2015</span>   
Student Advisory Board Representative | Maastricht University <span style="float:right;">2013 – 2014</span>   

